language: python
python:
- '3.5'
- '3.6'
install:
- pip install django
script:
- python -c "__import__('sys').exit(0)"
deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: YplLLYBUY03shdjlFz1uFzYyiwF9QnshqMYk633zO8VDLLmIKwPZzbXfTvyX50HtCpxllFmkSYRQG08z9axg3Vfc011fWacio86UuDkUDiQJSaf3np+C1wDvKvfv3IPVnAykawsSoHpZgiL+kwZzZ4z4P7VjGgYEIe7W/C/9743l+RipPxoPmXEm9Wb2itCXJW1x/jdlw8I9PW1roOxh91VAPaWRomVTlT+A9qHA/DMZTTKaXn/Qo5Hc41zQn97us7U1bZjTfwr4+KWGPWkR5tlI0tUNZXTeKx2ceNDY0TsUBroHeGXSGIwTCW0W0OUcG7L6hzXS/KLdG1EsbBtYZklIyp3qydmeB1XhTjpoBJPrjduc1KmkTNpNR8sKdxjd+D0lc8mzMKinI+yRP0ZfvL07hSmwzQCF5XX4dQWB8VTysXcub/Q9VpnK6h1zvcqoEbXSCTblpExZLxaERFlScFQYdE5NYwPrOOk0ZO7IEsaucMNURkqDyhv5jyfCPcS8ViBbT5ii9KfywxaDBeR08VzIYSY9DlAWLqercFVS0+Sto9XmhGpGfZH3kG91AgfcMGheoKXRgxK1uLODM5KJ4SJnYbolLxkxr0hkBAVIXBagng+ObTodkHvqnywazmwRqc3vJuOtkr52sITDxEqoVdtgygo2J73KVpn7ez+7A70=
